services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prueba_smart
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - smart_app

  postgres:
    image: postgres:15-alpine
    container_name: smart_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: smart_db
      POSTGRES_PASSWORD: smart_password
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/db:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - smart_app

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - smart_app

volumes:
  postgres_data:
    driver: local

networks:
  smart_app:
    driver: bridge